/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d6c5612e47793e2e91c8e4704d239d8a)
interface __BaseEnv_Env {
  HYPERDRIVE?: Hyperdrive
  AUTH_EMAIL_QUEUE?: Queue
  AUTH_EMAIL_DEAD_LETTER_QUEUE?: Queue
  VERSION_METADATA?: WorkerVersionMetadata
  APP_NAME?: 'Productivity Up'
  BETTER_AUTH_URL?: 'https://productivity-up-staging.ale-recchi.workers.dev' | 'https://productivity-up.com'
  EMAIL_FROM?: 'noreply-staging@productivity-up.com' | 'noreply@productivity-up.com'
  ENVIRONMENT?: 'staging' | 'production'
  BETTER_AUTH_SECRET?: string
  RESEND_API_KEY?: string
  USER_REALTIME?: DurableObjectNamespace<import('./src/server').UserRealtimeDurableObject>
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/server')
    durableNamespaces: 'UserRealtimeDurableObject'
  }
  interface StagingEnv {
    HYPERDRIVE: Hyperdrive
    AUTH_EMAIL_QUEUE: Queue
    AUTH_EMAIL_DEAD_LETTER_QUEUE: Queue
    VERSION_METADATA: WorkerVersionMetadata
    APP_NAME: 'Productivity Up'
    BETTER_AUTH_URL: 'https://productivity-up-staging.ale-recchi.workers.dev'
    EMAIL_FROM: 'noreply-staging@productivity-up.com'
    ENVIRONMENT: 'staging'
    BETTER_AUTH_SECRET: string
    RESEND_API_KEY: string
    USER_REALTIME: DurableObjectNamespace<import('./src/server').UserRealtimeDurableObject>
  }
  interface ProductionEnv {
    HYPERDRIVE: Hyperdrive
    AUTH_EMAIL_QUEUE: Queue
    AUTH_EMAIL_DEAD_LETTER_QUEUE: Queue
    VERSION_METADATA: WorkerVersionMetadata
    APP_NAME: 'Productivity Up'
    BETTER_AUTH_URL: 'https://productivity-up.com'
    EMAIL_FROM: 'noreply@productivity-up.com'
    ENVIRONMENT: 'production'
    BETTER_AUTH_SECRET: string
    RESEND_API_KEY: string
    USER_REALTIME: DurableObjectNamespace<import('./src/server').UserRealtimeDurableObject>
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      'APP_NAME' | 'BETTER_AUTH_URL' | 'EMAIL_FROM' | 'ENVIRONMENT' | 'BETTER_AUTH_SECRET' | 'RESEND_API_KEY'
    >
  > {}
}
