/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2268d716f4d94a716e8b6f862659da86)
interface __BaseEnv_Env {
  HYPERDRIVE?: Hyperdrive
  APP_NAME?: 'Productivity Up'
  BETTER_AUTH_URL?: 'https://productivity-up-staging.ale-recchi.workers.dev' | 'https://productivity-up.com'
  EMAIL_FROM?: 'noreply-staging@productivity-up.com' | 'noreply@productivity-up.com'
  BETTER_AUTH_SECRET?: string
  RESEND_API_KEY?: string
}
declare namespace Cloudflare {
  interface StagingEnv {
    HYPERDRIVE: Hyperdrive
    APP_NAME: 'Productivity Up'
    BETTER_AUTH_URL: 'https://productivity-up-staging.ale-recchi.workers.dev'
    EMAIL_FROM: 'noreply-staging@productivity-up.com'
    BETTER_AUTH_SECRET: string
    RESEND_API_KEY: string
  }
  interface ProductionEnv {
    HYPERDRIVE: Hyperdrive
    APP_NAME: 'Productivity Up'
    BETTER_AUTH_URL: 'https://productivity-up.com'
    EMAIL_FROM: 'noreply@productivity-up.com'
    BETTER_AUTH_SECRET: string
    RESEND_API_KEY: string
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'APP_NAME' | 'BETTER_AUTH_URL' | 'EMAIL_FROM' | 'BETTER_AUTH_SECRET' | 'RESEND_API_KEY'>
  > {}
}
