export const PRIVATE_OPERATION_NAMES = [
  'board.get',
  'board.completeDay',
  'board.getMigrationStep',
  'board.confirmMigrationStep',
  'board.getBuckets',
  'categories.create',
  'categories.list',
  'categories.update',
  'categories.delete',
  'tags.create',
  'tags.list',
  'tags.update',
  'tags.delete',
  'todos.create',
  'todos.list',
  'todos.update',
  'todos.move',
  'todos.delete',
] as const
